#ifndef TINYML_FEATURES_H
#define TINYML_FEATURES_H

#include <cstddef>
#include <cstdint>

// Computes TINYML_NUM_FRAMES x TINYML_N_MELS log-mel features from a raw PCM
// buffer into outFeatures (caller-allocated, TINYML_NUM_FRAMES*TINYML_N_MELS
// floats, row-major [frame][mel]). samples must be exactly TINYML_N_SAMPLES
// int16 values at TINYML_SAMPLE_RATE. Mirrors ml/features.py::extract_log_mel
// exactly — same framing and the same precomputed TINYML_MEL_FILTERBANK /
// TINYML_HANN_WINDOW from tinyml_feature_config.h (generated by
// ml/export_feature_config_to_c.py) — so on-device features match what the
// model in voice_tinyml_model.h was trained on. Returns false if sampleCount
// doesn't match.
bool computeLogMelFeatures(const int16_t *samples, size_t sampleCount, float *outFeatures);

#endif
